apiVersion: v1
kind: Service
metadata:
  name:  devops-course-rtp-service
  namespace: devops-course
spec:
  type: NodePort
  selector:
    app: devops-course-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000